name: Build Azel APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip openjdk-17-jdk zip unzip

    - name: Install Python tools
      run: |
        pip3 install --upgrade pip
        pip3 install buildozer cython

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Azel-APK
        path: bin/*.apk
        
